name: Scrape PCSP

on:
  workflow_dispatch:

  repository_dispatch:
    types:
      - webhook

  schedule:
    - cron: '0 18 * * 1-5'

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - uses: pnpm/action-setup@v2
        with:
          version: 7.18.2
          run_install: true
      - run: |
          npm run scrape
          git config user.name "Scraper bot"
          git config user.email "id00747372@usal.es"
          git diff --quiet && git diff --staged --quiet || git commit -am "[bot] update PCSP database"
          git push origin main
